[versions]
artifactory = "4.27.1"
cursegradle = "1.4.0"
licenser = "0.6.1"
loom = "1.+"
githubRelease = "2.2.12"
jgit = "[6.0.0,7.0.0)"
minotaur = "2.4.3"
gradle-publish = "1.2.0"

[libraries]
artifactory = { module = "org.jfrog.buildinfo:build-info-extractor-gradle", version.ref = "artifactory" }
cursegradle = { module = "gradle.plugin.com.matthewprenger:CurseGradle", version.ref = "cursegradle" }
licenser = { module = "gradle.plugin.org.cadixdev.gradle:licenser", version.ref = "licenser" }
loom = { module = "org.quiltmc:loom", version.ref = "loom" }
jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit"}
githubRelease = { module = "com.github.breadmoirai:github-release", version.ref = "githubRelease" }
minotaur = { module = "com.modrinth.minotaur:Minotaur", version.ref = "minotaur" }

[plugins]
licenser = { id = "org.cadixdev.licenser", version.ref = "licenser" }
gradle-pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "gradle-publish"}
