[versions]
cursegradle = "1.4.0"
licenser = "2.2.1"
loom = "1.14-SNAPSHOT"
githubRelease = "2.2.12"
jgit = "[6.0.0,7.0.0)"
minotaur = "2.8.7"
gradle-publish = "1.2.1"
junit = "6.0.2"
mockk = "1.13.14"

[libraries]
cursegradle = { module = "gradle.plugin.com.matthewprenger:CurseGradle", version.ref = "cursegradle" }
licenser = { module = "dev.yumi.gradle.licenser:dev.yumi.gradle.licenser.gradle.plugin", version.ref = "licenser" }
loom = { module = "net.fabricmc:fabric-loom", version.ref = "loom" }
jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit"}
githubRelease = { module = "com.github.breadmoirai:github-release", version.ref = "githubRelease" }
minotaur = { module = "com.modrinth.minotaur:Minotaur", version.ref = "minotaur" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }

[plugins]
licenser = { id = "dev.yumi.gradle.licenser", version.ref = "licenser" }
gradle-pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "gradle-publish"}
